// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.BD;

namespace ProyectoFinal.BD.Migrations
{
    [DbContext(typeof(CentrosSaludContext))]
    [Migration("20200519153740_CambioDeNombresCAPS2")]
    partial class CambioDeNombresCAPS2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoFinal.Modelos.CentroSalud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("RestriccionEdad")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CentrosSalud");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Leopoldo Marechal 1712",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.717370000000003,
                            Longitud = -62.227370000000001,
                            Nombre = "9 de Noviembre",
                            RestriccionEdad = "",
                            Telefono = 4822622
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Humboldt 3758",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.739649999999997,
                            Longitud = -62.212719999999997,
                            Nombre = "12 de Octubre",
                            RestriccionEdad = "",
                            Telefono = 4811397
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "25 de Mayo 396",
                            HorarioAtencion = "Las 24 hs",
                            Latitud = -38.729410000000001,
                            Longitud = -62.262650000000001,
                            Nombre = "A. Menghini",
                            RestriccionEdad = "",
                            Telefono = 4840157
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Los Adobes 424",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.682989999999997,
                            Longitud = -62.215170000000001,
                            Nombre = "Aldea Romana",
                            RestriccionEdad = "",
                            Telefono = 4862444
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "3 de Febrero 1658",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.724510000000002,
                            Longitud = -62.237690000000001,
                            Nombre = "Anchorena",
                            RestriccionEdad = "",
                            Telefono = 4815400
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Nicaragua 2953",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.690530000000003,
                            Longitud = -62.293439999999997,
                            Nombre = "Avellaneda",
                            RestriccionEdad = "",
                            Telefono = 4888350
                        },
                        new
                        {
                            Id = 7,
                            Direccion = "Lugones 46",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.690689999999996,
                            Longitud = -62.304180000000002,
                            Nombre = "Barrio Latino",
                            RestriccionEdad = "",
                            Telefono = 4889859
                        },
                        new
                        {
                            Id = 8,
                            Direccion = "Chiclana 1974",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.747190000000003,
                            Longitud = -62.229520000000001,
                            Nombre = "Barrio Obrero",
                            RestriccionEdad = "",
                            Telefono = 4821674
                        },
                        new
                        {
                            Id = 9,
                            Direccion = "Charcas 906",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.715159999999997,
                            Longitud = -62.24924,
                            Nombre = "Bella Vista",
                            RestriccionEdad = "",
                            Telefono = 4565569
                        },
                        new
                        {
                            Id = 10,
                            Direccion = "Alberti 215",
                            HorarioAtencion = "Las 24 hs",
                            Latitud = -38.700319999999998,
                            Longitud = -62.284280000000003,
                            Nombre = "Cabildo",
                            RestriccionEdad = "",
                            Telefono = 4918250
                        },
                        new
                        {
                            Id = 11,
                            Direccion = "Esmeralda 1450",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.748260000000002,
                            Longitud = -62.245559999999998,
                            Nombre = "CIC Spurr",
                            RestriccionEdad = "",
                            Telefono = 4511862
                        },
                        new
                        {
                            Id = 12,
                            Direccion = "O’Higgins 1637",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.734250000000003,
                            Longitud = -62.283949999999997,
                            Nombre = "Colón",
                            RestriccionEdad = "",
                            Telefono = 4554524
                        },
                        new
                        {
                            Id = 13,
                            Direccion = "D`Orbigny 2578",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.72907,
                            Longitud = -62.223500000000001,
                            Nombre = "Don Bosco",
                            RestriccionEdad = "",
                            Telefono = 4814880
                        },
                        new
                        {
                            Id = 14,
                            Direccion = "Avda. Arias 1730",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.750830000000001,
                            Longitud = -62.268889999999999,
                            Nombre = "Enrique Julio",
                            RestriccionEdad = "",
                            Telefono = 4556898
                        },
                        new
                        {
                            Id = 15,
                            Direccion = "Viamonte 2853",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.699939999999998,
                            Longitud = -62.301450000000003,
                            Nombre = "Estomba",
                            RestriccionEdad = "",
                            Telefono = 4889026
                        },
                        new
                        {
                            Id = 16,
                            Direccion = "La Rioja 5700",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.752609999999997,
                            Longitud = -62.176259999999999,
                            Nombre = "Grünbein",
                            RestriccionEdad = "",
                            Telefono = 4810938
                        },
                        new
                        {
                            Id = 17,
                            Direccion = "Maldonado 671",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.710299999999997,
                            Longitud = -62.293860000000002,
                            Nombre = "Kilómetro 5",
                            RestriccionEdad = "",
                            Telefono = 4565567
                        },
                        new
                        {
                            Id = 18,
                            Direccion = "Humboldt 56",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.708159999999999,
                            Longitud = -62.253019999999999,
                            Nombre = "La Falda - Vacunatorio",
                            RestriccionEdad = "",
                            Telefono = 4554626
                        },
                        new
                        {
                            Id = 19,
                            Direccion = "Gurruchaga 40",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.705910000000003,
                            Longitud = -62.413710000000002,
                            Nombre = "Laureano Muñiz - Vacunatorio",
                            RestriccionEdad = "",
                            Telefono = 4847220
                        },
                        new
                        {
                            Id = 20,
                            Direccion = "Adrián Veres y Martin Gil",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.719299999999997,
                            Longitud = -62.315089999999998,
                            Nombre = "Leandro Piñeiro",
                            RestriccionEdad = "",
                            Telefono = 4546309
                        },
                        new
                        {
                            Id = 21,
                            Direccion = "Lautaro y Paul Harris",
                            HorarioAtencion = "Las 24 hs",
                            Latitud = -38.775539999999999,
                            Longitud = -62.27122,
                            Nombre = "Leonor Capelli",
                            RestriccionEdad = "",
                            Telefono = 4573132
                        },
                        new
                        {
                            Id = 22,
                            Direccion = "Felix Frías 850",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.747889999999998,
                            Longitud = -62.285899999999998,
                            Nombre = "Loma Paraguaya",
                            RestriccionEdad = "",
                            Telefono = 4565592
                        },
                        new
                        {
                            Id = 23,
                            Direccion = "Enrique Julio 806",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.708060000000003,
                            Longitud = -62.299720000000001,
                            Nombre = "Lujan",
                            RestriccionEdad = "",
                            Telefono = 4888351
                        },
                        new
                        {
                            Id = 24,
                            Direccion = "Richieri 2535",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.71734,
                            Longitud = -62.319479999999999,
                            Nombre = "Maldonado",
                            RestriccionEdad = "",
                            Telefono = 4550257
                        },
                        new
                        {
                            Id = 25,
                            Direccion = "Mendoza 1250",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.720500000000001,
                            Longitud = -62.293309999999998,
                            Nombre = "Mariano Moreno",
                            RestriccionEdad = "",
                            Telefono = 4552088
                        },
                        new
                        {
                            Id = 26,
                            Direccion = "Laudelino Cruz 1892",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.708684599999998,
                            Longitud = -62.237235699999999,
                            Nombre = "Miramar",
                            RestriccionEdad = "",
                            Telefono = 4552417
                        },
                        new
                        {
                            Id = 27,
                            Direccion = "19 de Mayo 769",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.708269999999999,
                            Longitud = -62.26052,
                            Nombre = "Naposta",
                            RestriccionEdad = "",
                            Telefono = 4565562
                        },
                        new
                        {
                            Id = 28,
                            Direccion = "Líbano 589",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.726959999999998,
                            Longitud = -62.289850000000001,
                            Nombre = "Noroeste",
                            RestriccionEdad = "",
                            Telefono = 4556878
                        },
                        new
                        {
                            Id = 29,
                            Direccion = "Vieytes 1616",
                            HorarioAtencion = "08:00 a 18:00",
                            Latitud = -38.717370000000003,
                            Longitud = -62.227370000000001,
                            Nombre = "Norte",
                            RestriccionEdad = "",
                            Telefono = 4888267
                        },
                        new
                        {
                            Id = 30,
                            Direccion = "Witcomb 3900",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.676279999999998,
                            Longitud = -62.296109999999999,
                            Nombre = "Nueva Belgrano",
                            RestriccionEdad = "",
                            Telefono = 4888268
                        },
                        new
                        {
                            Id = 31,
                            Direccion = "Jujuy 946",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.725650000000002,
                            Longitud = -62.296169999999996,
                            Nombre = "Pampa Central",
                            RestriccionEdad = "",
                            Telefono = 4556939
                        },
                        new
                        {
                            Id = 32,
                            Direccion = "Lauquen 356",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.697719999999997,
                            Longitud = -62.211730000000003,
                            Nombre = "Patagonia",
                            RestriccionEdad = "",
                            Telefono = 4862440
                        },
                        new
                        {
                            Id = 33,
                            Direccion = "Misiones 754",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.73527,
                            Longitud = -62.263350000000003,
                            Nombre = "Pedro Pico",
                            RestriccionEdad = "",
                            Telefono = 4565559
                        },
                        new
                        {
                            Id = 34,
                            Direccion = "Estados Unidos 503",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.738199999999999,
                            Longitud = -62.253799999999998,
                            Nombre = "Rivadavia",
                            RestriccionEdad = "",
                            Telefono = 4556927
                        },
                        new
                        {
                            Id = 35,
                            Direccion = "Venezuela 296",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.739150000000002,
                            Longitud = -62.245719999999999,
                            Nombre = "Rosario Sur",
                            RestriccionEdad = "",
                            Telefono = 4821625
                        },
                        new
                        {
                            Id = 36,
                            Direccion = "Reconquista 2045",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.770603999999999,
                            Longitud = -62.245449999999998,
                            Nombre = "Saladero",
                            RestriccionEdad = "",
                            Telefono = 4570427
                        },
                        new
                        {
                            Id = 37,
                            Direccion = "Alberti 477",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.696959999999997,
                            Longitud = -62.280160000000002,
                            Nombre = "San Cayetano",
                            RestriccionEdad = "",
                            Telefono = 4888366
                        },
                        new
                        {
                            Id = 38,
                            Direccion = "Pacifico 154",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.736339999999998,
                            Longitud = -62.292070000000002,
                            Nombre = "San Dionisio",
                            RestriccionEdad = "",
                            Telefono = 4550211
                        },
                        new
                        {
                            Id = 39,
                            Direccion = "Reconquista 3084",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.779440000000001,
                            Longitud = -62.256219999999999,
                            Nombre = "San Jose Obrero",
                            RestriccionEdad = "",
                            Telefono = 4570474
                        },
                        new
                        {
                            Id = 40,
                            Direccion = "Bermudez 1580",
                            HorarioAtencion = "extensión CS 9 de noviembre",
                            Latitud = -38.720199999999998,
                            Longitud = -62.235520000000001,
                            Nombre = "Sanchez Elia",
                            RestriccionEdad = "",
                            Telefono = 4815419
                        },
                        new
                        {
                            Id = 41,
                            Direccion = "Pellegrini 638",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.721600000000002,
                            Longitud = -62.250210000000003,
                            Nombre = "Tiro Federal",
                            RestriccionEdad = "",
                            Telefono = 4554598
                        },
                        new
                        {
                            Id = 42,
                            Direccion = "Uruguay 463",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.701560000000001,
                            Longitud = -62.274769999999997,
                            Nombre = "Universitario",
                            RestriccionEdad = "",
                            Telefono = 4565581
                        },
                        new
                        {
                            Id = 43,
                            Direccion = "Larrea 5450",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.714779999999998,
                            Longitud = -62.311369999999997,
                            Nombre = "Villa Bordeu",
                            RestriccionEdad = "",
                            Telefono = 4885679
                        },
                        new
                        {
                            Id = 44,
                            Direccion = "Fournier 1809",
                            HorarioAtencion = "extensión CS 9 de noviembre",
                            Latitud = -38.723370000000003,
                            Longitud = -62.226770000000002,
                            Nombre = "Villa Amaducci",
                            RestriccionEdad = "",
                            Telefono = 4810155
                        },
                        new
                        {
                            Id = 45,
                            Direccion = "Juana Azurduy 1345",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.750140000000002,
                            Longitud = -62.275770000000001,
                            Nombre = "Villa Delfina",
                            RestriccionEdad = "",
                            Telefono = 4552271
                        },
                        new
                        {
                            Id = 46,
                            Direccion = "Berutti 2980",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.729419999999998,
                            Longitud = -62.2605,
                            Nombre = "Villa Esperanza",
                            RestriccionEdad = "",
                            Telefono = 4813677
                        },
                        new
                        {
                            Id = 47,
                            Direccion = "José Ingenieros 2235",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.69153,
                            Longitud = -62.263590000000001,
                            Nombre = "Villa Floresta",
                            RestriccionEdad = "",
                            Telefono = 4888365
                        },
                        new
                        {
                            Id = 48,
                            Direccion = "Rojas 4898",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.74982,
                            Longitud = -62.191670000000002,
                            Nombre = "Villa Gloria",
                            RestriccionEdad = "",
                            Telefono = 4817321
                        },
                        new
                        {
                            Id = 49,
                            Direccion = "Salinas Chicas 4150",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.714480000000002,
                            Longitud = -62.189450000000001,
                            Nombre = "Villa H. Green",
                            RestriccionEdad = "",
                            Telefono = 4862447
                        },
                        new
                        {
                            Id = 50,
                            Direccion = "Washington 232",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.730409999999999,
                            Longitud = -62.24653,
                            Nombre = "Villa Mitre",
                            RestriccionEdad = "",
                            Telefono = 4817261
                        },
                        new
                        {
                            Id = 51,
                            Direccion = "Pilcaniyen 259",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.746099999999998,
                            Longitud = -62.225990000000003,
                            Nombre = "Villa Muñiz",
                            RestriccionEdad = "",
                            Telefono = 4811080
                        },
                        new
                        {
                            Id = 52,
                            Direccion = "Pacifico 1925",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.721699999999998,
                            Longitud = -62.31221,
                            Nombre = "Villa Nocito",
                            RestriccionEdad = "",
                            Telefono = 4550240
                        },
                        new
                        {
                            Id = 53,
                            Direccion = "Misiones 1570",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.742669999999997,
                            Longitud = -62.272080000000003,
                            Nombre = "Villa Ressia",
                            RestriccionEdad = "",
                            Telefono = 4565591
                        },
                        new
                        {
                            Id = 54,
                            Direccion = "Libertad 1955",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.755940000000002,
                            Longitud = -62.261400000000002,
                            Nombre = "Villa Rosas",
                            RestriccionEdad = "",
                            Telefono = 4552418
                        },
                        new
                        {
                            Id = 55,
                            Direccion = "Tarija 1350",
                            HorarioAtencion = "08:00 a 14:00",
                            Latitud = -38.75788,
                            Longitud = -62.246609999999997,
                            Nombre = "Villa Serra",
                            RestriccionEdad = "",
                            Telefono = 4560139
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.Colectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Colectivos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Linea = "319"
                        },
                        new
                        {
                            Id = 2,
                            Linea = "500"
                        },
                        new
                        {
                            Id = 3,
                            Linea = "502"
                        },
                        new
                        {
                            Id = 4,
                            Linea = "503"
                        },
                        new
                        {
                            Id = 5,
                            Linea = "504"
                        },
                        new
                        {
                            Id = 6,
                            Linea = "505"
                        },
                        new
                        {
                            Id = 7,
                            Linea = "506"
                        },
                        new
                        {
                            Id = 8,
                            Linea = "507"
                        },
                        new
                        {
                            Id = 9,
                            Linea = "509"
                        },
                        new
                        {
                            Id = 10,
                            Linea = "512"
                        },
                        new
                        {
                            Id = 11,
                            Linea = "513"
                        },
                        new
                        {
                            Id = 12,
                            Linea = "513 EX"
                        },
                        new
                        {
                            Id = 13,
                            Linea = "514"
                        },
                        new
                        {
                            Id = 14,
                            Linea = "516"
                        },
                        new
                        {
                            Id = 15,
                            Linea = "517"
                        },
                        new
                        {
                            Id = 16,
                            Linea = "518"
                        },
                        new
                        {
                            Id = 17,
                            Linea = "519"
                        },
                        new
                        {
                            Id = 18,
                            Linea = "519 A"
                        },
                        new
                        {
                            Id = 19,
                            Linea = "520"
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.ColectivoCentroSalud", b =>
                {
                    b.Property<int>("CentroSaludId")
                        .HasColumnType("int");

                    b.Property<int>("ColectivoId")
                        .HasColumnType("int");

                    b.HasKey("CentroSaludId", "ColectivoId");

                    b.HasIndex("ColectivoId");

                    b.ToTable("ColectivosCentrosSalud");

                    b.HasData(
                        new
                        {
                            CentroSaludId = 1,
                            ColectivoId = 1
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alergia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cardiología"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Clínica Médica"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Dermatología"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Endocrinología"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Estimulación Temprana"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Fonoaudiología"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Gastroenterología"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Ginecología"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Hematología"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Infectología"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Inmunizaciones"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Kinesiología"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Medicina Familiar"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Nefrología"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Neumonología"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Neurocirugía"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Neurología"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Nutrición"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Obstetricia"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Odontología"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Oftalmología"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Oncología"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Otorrinolaringología"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Pediatría"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Psicología"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Psicopedagogía"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Trabajo Social"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Traumatología y Ortopedia"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Urología"
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.EspecialidadCentroSalud", b =>
                {
                    b.Property<int>("CentroSaludId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.HasKey("CentroSaludId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("EspecialidadesCentrosSalud");

                    b.HasData(
                        new
                        {
                            CentroSaludId = 1,
                            EspecialidadId = 1
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.PracticaDiagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("PracticasDiagnosticos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ecografías"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Electrocardiogramas"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Electroencefalogramas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Endoscopías"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Laboratorio de Análisis Clínicos"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Laboratorio de Anatomía Patológica"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Laboratorio de Hematología"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Radiografías"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Tomografías"
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.PracticaDiagnosticoCentroSalud", b =>
                {
                    b.Property<int>("CentroSaludId")
                        .HasColumnType("int");

                    b.Property<int>("PracticaDiagnosticoId")
                        .HasColumnType("int");

                    b.HasKey("CentroSaludId", "PracticaDiagnosticoId");

                    b.HasIndex("PracticaDiagnosticoId");

                    b.ToTable("PracticasDiagnosticoCentrosSalud");

                    b.HasData(
                        new
                        {
                            CentroSaludId = 1,
                            PracticaDiagnosticoId = 1
                        });
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.ColectivoCentroSalud", b =>
                {
                    b.HasOne("ProyectoFinal.Modelos.CentroSalud", "CentroSalud")
                        .WithMany("ColectivosCentroSalud")
                        .HasForeignKey("CentroSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal.Modelos.Colectivo", "Colectivo")
                        .WithMany("ColectivosCentroSalud")
                        .HasForeignKey("ColectivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.EspecialidadCentroSalud", b =>
                {
                    b.HasOne("ProyectoFinal.Modelos.CentroSalud", "CentroSalud")
                        .WithMany("EspecialidadesCentroSalud")
                        .HasForeignKey("CentroSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal.Modelos.Especialidad", "Especialidad")
                        .WithMany("EspecialidadesCentroSalud")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinal.Modelos.PracticaDiagnosticoCentroSalud", b =>
                {
                    b.HasOne("ProyectoFinal.Modelos.CentroSalud", "CentroSalud")
                        .WithMany("PracticasDiagnosticoCentroSalud")
                        .HasForeignKey("CentroSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal.Modelos.PracticaDiagnostico", "PracticaDiagnostico")
                        .WithMany("PracticasDiagnosticoCentroSalud")
                        .HasForeignKey("PracticaDiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
